config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  mount Sidekiq::Web => '/sidekiq'
  root 'reminders#index'

  devise_scope :user do
    root 'devise/sessions#new', as: :unauthenticated_root
  end

  resources :reminders, except: [:create, :new, :destroy]
  resources :short_messages, except: [:create, :new, :destroy]
  resources :short_message_templates, except: [:create, :new, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  belongs_to :sms_template, class_name: 'ShortMessageTemplate', foreign_key: 'sms_template_id'

  def period_time
    return 0 unless period_type.present?
    period.send("#{period_type}".pluralize) 
  end

  def period_time_text
    [period, period_type_humanize].join(' ')
  end

  def period_type_humanize
    period > 1 ? period_type.pluralize : period_type
  end
end

app/models/short_message.rb
class ShortMessage < ApplicationRecord
  belongs_to :user
  belongs_to :reminder

  enum status: [:unsent, :sent, :failed]
  enum kind: [:realtime, :schedule]

  validates :phone_number, :content, presence: true

  scope :scheduled, -> { where(kind: 'schedule') }
end

app/models/short_message_template.rb
class ShortMessageTemplate < ApplicationRecord
  validates :name, presence: true

  scope :enabled, -> { where(enabled: true) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reminders
  has_many :short_messages
  validates :email, :phone, presence: true

  after_create :after_sign_up
  before_create :format_phone_number

  private

  def format_phone_number
    self.phone.slice! '0'
    self.phone = "+84#{self.phone}"
    self.phone
  end

  def after_sign_up
    send_welcome_sms
    create_schedule_sms
  end

  def send_welcome_sms
    ShortMessage::WelcomeSmsSender.new(user_id: id).perform
  end

  def create_schedule_sms
    ShortMessage::ScheduleSmsCreator.new(params: schedule_sms_params).perform
  end

  def schedule_sms_params
    {
      user_id: id,
      reminder_id: reminder&.id,
      expected_send_date: created_at + reminder.period_time
    }
  end

  def reminder
    @reminder ||= Reminder.find_by(title: 'Notify SMS after 7 days registration')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :reminder, only: [:show, :edit, :update, :destroy]

  def index
    @reminders = Reminder.all
    render 'index'
  end

  def show
  end

  def edit
    render 'edit'
  end

  def update
    if @reminder.update(reminder_params)
      flash[:success] = 'Update reminder successfully'
      redirect_to reminders_path
    else
      flash[:error] = 'Update reminder failed'
      render :edit
    end
  end

  private

  def reminder
    @reminder ||= Reminder.find(params[:id])
  end

  def reminder_params
    params.require(:reminder).permit(:title, :period, :period_type)
  end
end

app/controllers/short_message_templates_controller.rb
class ShortMessageTemplatesController < ApplicationController
  before_action :short_message_template, only: [:show, :edit, :update, :destroy]

  def index
    @short_message_templates = ShortMessageTemplate.all
    render 'index'
  end

  def show
  end

  def edit
    render 'edit'
  end

  def update
    if @short_message_template.update(short_message_template_params)
      flash[:success] = 'Update SMS template successfully'
      redirect_to short_message_templates_path
    else
      flash[:error] = 'Update SMS template failed'
      render :edit
    end
  end

  private

  def short_message_template
    @short_message_template ||= ShortMessageTemplate.find(params[:id])
  end

  def short_message_template_params
    params.require(:short_message_template).permit(:name, :content, :enabled)
  end
end

app/controllers/short_messages_controller.rb
class ShortMessagesController < ApplicationController
  before_action :short_message, only: [:show, :edit, :update, :destroy]

  def index
    @short_messages = ShortMessage.all
    render 'index'
  end

  def show
  end

  def edit
  end

  def update
    if @short_message.update(short_message_params)
      flash[:success] = 'Update SMS successfully'
      redirect_to short_messages_path
    else
      flash[:error] = 'Update SMS failed'
      render :edit
    end
  end

  private

  def short_message
    @short_message ||= ShortMessage.find(params[:id])
  end

  def short_message_params
    params.require(:short_message).permit(:phone_number, :content, :expected_send_date, 
      :short_message_template_id, :status, :kind)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def date_parse_strftime(date)
    return unless date.present?
    date.strftime("%d-%m-%Y %H:%M:%S")
  end

  def boolean_humanize(boolean)
    boolean.to_s.humanize
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReminderApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Reminder', reminders_path %>
    <%= link_to 'SMS', short_messages_path %>
    <%= link_to 'SMS Template', short_message_templates_path %>
    <%= yield %>
  </body>
</html>

app/views/reminders/_form.html.haml
= form_for :reminder, url: reminder_path(@reminder), method: :put, local: true do |form|
  %p 
    Title
    = form.text_field :title
  %p
    Due After
    = form.number_field :period

  %p
    = form.submit
 
= link_to 'Back', reminders_path

app/views/reminders/edit.html.haml
%h3 Edit reminder
= render partial: 'form'

app/views/reminders/index.html.haml
%h1 Reminders

%table
  %tr
    %th Title
    %th Due After
    %th Actions
 
  - @reminders.each do |reminder|
    %tr
      %td= reminder.title
      %td= reminder.period_time_text
      %td= link_to 'Edit', edit_reminder_path(reminder) 

app/views/short_message_templates/_form.html.haml
= form_for :short_message_template, url: short_message_template_path(@short_message_template), method: :put, local: true do |form|
  %p 
    = form.label :name
    = form.text_field :name
 
  %p
    = form.label :content
    = form.text_area :content

  %p
    Enabled?
    = form.check_box :enabled
 
  %p
    = form.submit
 
= link_to 'Back', short_message_templates_path

app/views/short_message_templates/edit.html.haml
Edit SMS Template
= render partial: 'form'

app/views/short_message_templates/index.html.haml
%h1 SMS Templates
      
%table
  %tr
    %th{width: '300px'} Name
    %th{width: '500px'} Content
    %th{width: '100px'} Status
    %th Actions
 
  - @short_message_templates.each do |short_message_template|
    %tr
      %td{width: '300px'}= short_message_template.name
      %td{width: '500px'}= short_message_template.content
      %td{width: '100px'}= boolean_humanize(short_message_template.enabled)
      %td= link_to 'Edit', edit_short_message_template_path(short_message_template) 

app/views/short_messages/_form.html.haml
= form_for :short_message, url: short_message_path(@short_message), method: :put, local: true do |form|
  %p 
    Phone Number
    = form.text_field :phone_number
 
  %p
    Content
    = form.text_area :content
 
  %p
    = form.submit
 
= link_to 'Back', short_messages_path

app/views/short_messages/edit.html.haml
%h3 Edit SMS
= render partial: 'short_messages/form'

app/views/short_messages/index.html.haml
%h1 Short Messages

%table
  %tr
    %th Phone Number
    %th{width: '500px'} Content
    %th{width: '100px'} Status
    %th{width: '200px'} Expected Send Date
    %th Actions
 
  - @short_messages.each do |short_message|
    %tr
      %td= short_message.phone_number
      %td{width: '500px'}= short_message.content
      %td{width: '100px', style: 'text-align: center'}= short_message.status.humanize
      %td{width: '200px'}= date_parse_strftime(short_message.expected_send_date)
      %td= link_to 'Show SMS', short_message_path(short_message) 
      - if short_message.unsent?
        %td= link_to 'Edit SMS', edit_short_message_path(short_message)

app/views/short_messages/show.html.haml
%h3 Short Message Details

%p
  %strong Phone Number:
  = @short_message.phone_number
 
%p
  %strong Message Content:
  = @short_message.content

%p
  %strong Status:
  = @short_message.status.humanize

- if @short_message.expected_send_date.present?
  %p
    %strong Expected Send Date:
    = date_parse_strftime(@short_message.expected_send_date)

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>